version: "3.7"
services:
  redis:
    image: redis
    container_name: redis
    networks:
      - wagile
    expose:
      - 6379
  main_app:
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    build: .
    ports:
      - "3000:3000"
    networks:
      - wagile
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
networks:
  wagile:
    driver: bridge
